library(readxl)
library(readr)
library(lubridate)
library(dplyr)
getwd()
maestro<-read_rds("DATOS/Datos Originales/maestroestr.RDS")
objetivos<-read_rds("DATOS/Datos Originales/objetivos.RDS")
tickets<-read_rds("DATOS/Datos Originales/tickets_enc.RDS")
datos<-tickets %>%  inner_join(maestro, by = "cod_est" )
datos$dia<-ymd(datos$dia)
